const books = [
  {
    id:1,
    name: "Pai Rico, Pai Pobre",
    author: "Robert T. Kiyosaki",
    pages: 336,
    year: 2017,
    price: "R$ 44,90",
    category: "Finanças",
  },
  {
    id:2,
    name: "1984",
    author: "George Orwell",
    pages: 416,
    year: 2017,
    price: "R$ 39,90",
    category: "Romance",
  },

  {
    id:3,
    name: "O sol é para todos",
    author: "Harper Lee",
    pages: 350,
    year: 2006,
    price: "R$ 46,90",
    category: "Romance",
  },

  {
    id:4,
    name: "A Garota do Lago",
    author: "Charlie Donlea",
    pages: 296,
    year: 2017,
    price: "R$ 16,90",
    category: "Policial e Suspense",
  },
  {
    id:5,
    name: "Dracula",
    author: "Bram Stoker",
    pages: 432,
    year: 2019,
    price: "R$ 34,90",
    category: "Terror",
  },
  {
    id:6,
    name: "A Sultil Arte de Ligar o Foda-se",
    author: "Mark Manson",
    pages: 224,
    year: 2017,
    price: "R$ 39,90",
    category: "Desenvolvimento Pessoal",
  },
  {
    id:7,
    name: "Seja Foda!",
    author: "Caio Carneiro",
    pages: 192,
    year: 2017,
    price: "R$ 44,90",
    category: "Marketing e Vendas",
  },
  {
    id:8,
    name: "Quem sabe faz a Hora!",
    author: "Mario Sergio Cortella",
    pages: 172,
    year: 2021,
    price: "R$ 34,90",
    category: "Filosofia",
  },
];

module.exports = books //exportação do array para App.js
